version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=production
    container_name: react-app-prod
    ports:
      - 8080:80
    