version: "3.8"

services:
  react-app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    environment:
      - REACT_APP_NAME="dicky me"
    