FROM node:20-alpine

ENV LANG=C.UTF-8

# Set working directory.
WORKDIR /app

# Copy the package.json to working directory.
COPY ./app/package.json .

# Download the packages
RUN npm install

# Copy all files.
COPY ./app .

# Expose the port 3000.
EXPOSE 3000

# Start the server with CMD.
CMD ["npm", "start"]
